// Auto-generated from public/data/celestial_data.json — IAU 3-letter
// constellation abbreviation -> localized name (Ukrainian/English). Kept
// compact (~88 entries, ~3 KB) so the galaxy page can show a constellation
// name without loading the 891 KB celestial_data.json. Regenerate via this
// _gen_constellation_names.py one-shot if the source data changes.

export const CONSTELLATION_NAMES = {
  AND: { uk: "Андромеда", en: "Andromeda" },
  ANT: { uk: "Насос", en: "Antlia" },
  APS: { uk: "Райський Птах", en: "Apus" },
  AQL: { uk: "Орел", en: "Aquila" },
  AQR: { uk: "Водолій", en: "Aquarius" },
  ARA: { uk: "Жертовник", en: "Ara" },
  ARI: { uk: "Овен", en: "Aries" },
  AUR: { uk: "Візничий", en: "Auriga" },
  BOO: { uk: "Волопас", en: "Boötes" },
  CAE: { uk: "Різець", en: "Caelum" },
  CAM: { uk: "Жираф", en: "Camelopardalis" },
  CAP: { uk: "Козоріг", en: "Capricornus" },
  CAR: { uk: "Кіль", en: "Carina" },
  CAS: { uk: "Кассіопея", en: "Cassiopeia" },
  CEN: { uk: "Центавр", en: "Centaurus" },
  CEP: { uk: "Цефей", en: "Cepheus" },
  CET: { uk: "Кит", en: "Cetus" },
  CHA: { uk: "Хамелеон", en: "Chamaeleon" },
  CIR: { uk: "Циркуль", en: "Circinus" },
  CMA: { uk: "Великий Пес", en: "Canis Major" },
  CMI: { uk: "Малий Пес", en: "Canis Minor" },
  CNC: { uk: "Рак", en: "Cancer" },
  COL: { uk: "Голуб", en: "Columba" },
  COM: { uk: "Волосся Вероніки", en: "Coma Berenices" },
  CRA: { uk: "Південна Корона", en: "Corona Austrina" },
  CRB: { uk: "Північна Корона", en: "Corona Borealis" },
  CRT: { uk: "Чаша", en: "Crater" },
  CRU: { uk: "Південний Хрест", en: "Crux" },
  CRV: { uk: "Ворон", en: "Corvus" },
  CVN: { uk: "Гончі Пси", en: "Canes Venatici" },
  CYG: { uk: "Лебідь", en: "Cygnus" },
  DEL: { uk: "Дельфін", en: "Delphinus" },
  DOR: { uk: "Золота Риба", en: "Dorado" },
  DRA: { uk: "Дракон", en: "Draco" },
  EQU: { uk: "Малий Кінь", en: "Equuleus" },
  ERI: { uk: "Ерідан", en: "Eridanus" },
  FOR: { uk: "Піч", en: "Fornax" },
  GEM: { uk: "Близнюки", en: "Gemini" },
  GRU: { uk: "Журавель", en: "Grus" },
  HER: { uk: "Геркулес", en: "Hercules" },
  HOR: { uk: "Годинник", en: "Horologium" },
  HYA: { uk: "Гідра", en: "Hydra" },
  HYI: { uk: "Південна Гідра", en: "Hydrus" },
  IND: { uk: "Індіанець", en: "Indus" },
  LAC: { uk: "Ящірка", en: "Lacerta" },
  LEO: { uk: "Лев", en: "Leo" },
  LEP: { uk: "Заєць", en: "Lepus" },
  LIB: { uk: "Терези", en: "Libra" },
  LMI: { uk: "Малий Лев", en: "Leo Minor" },
  LUP: { uk: "Вовк", en: "Lupus" },
  LYN: { uk: "Рись", en: "Lynx" },
  LYR: { uk: "Ліра", en: "Lyra" },
  MEN: { uk: "Столова Гора", en: "Mensa" },
  MIC: { uk: "Мікроскоп", en: "Microscopium" },
  MON: { uk: "Єдиноріг", en: "Monoceros" },
  MUS: { uk: "Муха", en: "Musca" },
  NOR: { uk: "Косинець", en: "Norma" },
  OCT: { uk: "Октант", en: "Octans" },
  OPH: { uk: "Змієносець", en: "Ophiuchus" },
  ORI: { uk: "Оріон", en: "Orion" },
  PAV: { uk: "Павич", en: "Pavo" },
  PEG: { uk: "Пегас", en: "Pegasus" },
  PER: { uk: "Персей", en: "Perseus" },
  PHE: { uk: "Фенікс", en: "Phoenix" },
  PIC: { uk: "Живописець", en: "Pictor" },
  PSA: { uk: "Південна Риба", en: "Piscis Austrinus" },
  PSC: { uk: "Риби", en: "Pisces" },
  PUP: { uk: "Корма", en: "Puppis" },
  PYX: { uk: "Компас", en: "Pyxis" },
  RET: { uk: "Сітка", en: "Reticulum" },
  SCL: { uk: "Скульптор", en: "Sculptor" },
  SCO: { uk: "Скорпіон", en: "Scorpius" },
  SCT: { uk: "Щит", en: "Scutum" },
  SER: { uk: "Змія", en: "Serpens Cauda" },
  SEX: { uk: "Sextans", en: "Sextans" },
  SGE: { uk: "Стріла", en: "Sagitta" },
  SGR: { uk: "Стрілець", en: "Sagittarius" },
  TAU: { uk: "Телець", en: "Taurus" },
  TEL: { uk: "Телескоп", en: "Telescopium" },
  TRA: { uk: "Південний Трикутник", en: "Triangulum Australe" },
  TRI: { uk: "Трикутник", en: "Triangulum" },
  TUC: { uk: "Тукан", en: "Tucana" },
  UMA: { uk: "Велика Ведмедиця", en: "Ursa Major" },
  UMI: { uk: "Мала Ведмедиця", en: "Ursa Minor" },
  VEL: { uk: "Вітрила", en: "Vela" },
  VIR: { uk: "Діва", en: "Virgo" },
  VOL: { uk: "Летюча Риба", en: "Volans" },
  VUL: { uk: "Лисичка", en: "Vulpecula" },
};

export function constellationName(abbr, lang = 'uk') {
  if (!abbr) return null;
  const e = CONSTELLATION_NAMES[String(abbr).toUpperCase()];
  return e ? e[lang] || e.en : null;
}
